### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by LemonSpike**
*Total -- 151.00kb -> 133.25kb (11.75%)

/Guides/Resources/SortedPrefix/FewElements.png -- 73.60kb -> 64.27kb (12.67%)
/Guides/Resources/SortedPrefix/ManyElements.png -- 77.40kb -> 68.98kb (10.87%)

Signed-off-by: ImgBotApp <ImgBotHelp@gmail.com>

I use ImgBot for my repos (so does [Google 👀](https://imgbot.net)), so thought it might be useful to include for this repo as well. Original PR on my fork is [here](https://github.com/LemonSpike/swift-algorithms/pull/1). And the bot is _free_ for Open Source projects like this one.

Let me know your thoughts. 

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](../CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Review by CertifiedRice — CHANGES_REQUESTED** [review]
idk, maybe try using text next time.

**Comment by LemonSpike** [comment]
Sorry, who are you?

**Comment by natecook1000** [comment]
Thanks @LemonSpike — this is fine; we're using the Swift CI infrastructure for testing, and don't plan to add bot dependencies here.

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
