### PR TITLE
remove the build warning descripted in #232 

### PR DESCRIPTION
**Pull request by wangzhizhou**
#232 remove this build warning display as follow:

image

### CODE REVIEW

**Comment by wangzhizhou** [comment]
@swift-ci please test

**Comment by wangzhizhou** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Review by glessard — APPROVED** [review]

**Comment by wangzhizhou** [comment]
Is this change be merge into main branch?

**Review by Naveen-C-Ramachandrappa — APPROVED** [review]

**Comment by glessard** [comment]
@wangzhizhou It's probably better to exclude the file as in https://github.com/apple/swift-algorithms/pull/237, since a resource would always get copied alongside the binary.

**Comment by natecook1000** [comment]
Thanks, @wangzhizhou! This should be resolved by #240.

**Comment by wangzhizhou** [comment]
> Thanks, @wangzhizhou! This should be resolved by #240.

Ok

**Pull request closed without merging**
