### PR TITLE
Remove the inout on reductions(into:_:) to be consistent with the stdlib reduce(into:_)

### PR DESCRIPTION
**Pull request by kylemacomber**
### Checklist
- [ ] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](../CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by kylemacomber** [comment]
@swift-ci please test

**Comment by kylemacomber** [comment]
@swift-ci please test

**Comment by kylemacomber** [comment]
cc @danielctull

**Comment by danielctull** [comment]
Thanks for fixing that. I’m not sure where the idea that it should be `inout` came from! 🙂

**Pull request merged**
